### ISSUE TITLE
Kernel dies when using tagged release v1.0

### ISSUE THREAD

**Issue by zepedar** [binder-examples/conda_environment#7]
When using the links in the README to run the example binder, the kernel dies during the last step of the notebook.

I copied and changed the url to use master, and that branch works fine.  Also noticed those binder links are using beta.mybinder.org instead of mybinder.org.

I suggest maybe creating a new release tag and updating the links in README.md.

**Comment by choldgraf** [comment]
thanks so much for catching this! I just updated the README to point to master instead of the tagged version
